name: Sync to Hugging Face Spaces

#  触发条件：发现 main 分支有代码 push 进来，就可以推送。
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # 1. 把 GitHub 仓库里的代码拉取到自动化服务器上
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # 2. 推送到 Hugging Face Spaces 对应的空间里
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://zxyy11:$HF_TOKEN@huggingface.co/spaces/zxyy11/image-algorithm main
